# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sxp/all/sxp.rbi
#
# sxp-1.1.0
module SXP
  def self.parse(input, **options); end
  def self.parse_all(input, **options); end
  def self.parse_file(filename, **options); end
  def self.parse_files(*filenames); end
  def self.parse_uri(url, **options); end
  def self.parse_url(url, **options); end
  def self.read(input, **options); end
  def self.read_all(input, **options); end
  def self.read_file(filename, **options); end
  def self.read_files(*filenames); end
  def self.read_uri(url, **options); end
  def self.read_url(url, **options); end
  def self.write(sxp, output = nil); end
end
module SXP::VERSION
  def self.to_a; end
  def self.to_s; end
  def self.to_str; end
end
class Symbol
  def keyword?; end
  def to_sxp; end
end
class RDF::URI
  def lexical; end
  def lexical=(value); end
  def to_sxp; end
end
class Object < BasicObject
  def to_sxp; end
end
class NilClass
  def to_sxp; end
end
class FalseClass
  def to_sxp; end
end
class TrueClass
  def to_sxp; end
end
class String
  def to_sxp; end
end
class Integer < Numeric
  def to_sxp; end
end
class BigDecimal < Numeric
  def to_sxp; end
end
class Float < Numeric
  def to_sxp; end
end
class Array
  def to_sxp; end
end
class Time
  def to_sxp; end
end
class Regexp
  def to_sxp; end
end
class RDF::Node
  def to_sxp; end
end
class RDF::Literal
  def to_sxp; end
end
class RDF::Query
  def to_sxp; end
end
class RDF::Query::Pattern < RDF::Statement
  def to_sxp; end
end
class RDF::Query::Variable
  def to_sxp; end
end
